inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "vendor/**/*"
    - "bin/**/*"
    - "spec/**/*"
    - "config/puma.rb"
    - "config/boot.rb"
    - "config/environments/**/*"
    - "config/initializers/devise.rb"
    - "node_modules/**/*"
    - "tmp/**/*"

# --- Layout ---
Layout/LineLength:
  Max: 200

# --- Lint: Disabled (callbacks need signatures) ---
Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

# --- Style: Disabled (noise or readability preference) ---
Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# --- Rails: Disabled (intentional usage) ---
Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
